# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQzBvekFqjI0_MPzQBaaOfYYJR_YVF-4
"""

import math

# --- 1. Data Initialization ---
movies = {
    "The Grand Adventure": {"price": 12.00, "seats": [
        "A1", "A2", "A3", "A4", "A5", "A6",
        "B1", "B2", "B3", "B4", "B5", "B6",
        "C1", "C2", "C3", "C4", "C5", "C6"
    ]},
    "Mystery of the Old House": {"price": 10.50, "seats": [
        "D1", "D2", "D3", "D4", "D5", "D6",
        "E1", "E2", "E3", "E4", "E5", "E6",
        "F1", "F2", "F3", "F4", "F5", "F6"
    ]},
    "Sci-Fi Odyssey": {"price": 15.00, "seats": [
        "G1", "G2", "G3", "G4", "G5", "G6",
        "H1", "H2", "H3", "H4", "H5", "H6",
        "I1", "I2", "I3", "I4", "I5", "I6","I7"
    ]}
}

available_seats = {
    movie_name: set(details["seats"]) for movie_name, details in movies.items()
}

booked_seats = {
    movie_name: set() for movie_name in movies.keys()
}

users = {
    "user1": "pass1",
    "user2": "pass2",
    "alice": "password",
    "bob": "12345"
}

# --- 2. User Authentication ---
def login():
    attempts = 0
    while attempts < 3:
        username = input("Enter username: ").strip()
        password = input("Enter password: ").strip()

        if username in users and users[username] == password:
            print(f"Welcome, {username}!")
            return username
        else:
            print("Invalid username or password. Please try again.")
            attempts += 1
    print("Too many failed login attempts. Exiting.")
    exit()

# --- 3. Movie Selection ---
def display_movies():
    print("\n--- Available Movies ---")
    for movie, details in movies.items():
        print(f"- {movie} (Price: ${details['price']:.2f})")

def select_movie():
    while True:
        display_movies()
        chosen_movie = input("\nEnter the name of the movie you want to watch: ").strip()
        if chosen_movie in movies:
            print(f"You selected: {chosen_movie}")
            return chosen_movie
        else:
            print("Invalid movie name. Please choose from the list.")

# --- 4. Seat Selection ---
def display_available_seats(movie_name):
    print(f"\n--- Available Seats for {movie_name} ---")
    seats = sorted(list(available_seats[movie_name]))
    if not seats:
        print("No seats available for this movie.")
        return

    # Display seats in a grid-like format for better readability
    seats_per_row = 6 # You can adjust this number
    for i in range(0, len(seats), seats_per_row):
        print(" ".join(seats[i:i + seats_per_row]))

def select_seats(movie_name):
    chosen_seats = set()
    while True:
        display_available_seats(movie_name)
        if not available_seats[movie_name]:
            print("Sorry, no seats are available for this movie.")
            return set()

        seat_input = input("Enter the seat numbers you want to book (e.g., A1 B2), or 'done' to finish: ").upper().strip()
        if seat_input == 'DONE':
            break

        input_seats = set(seat_input.split())
        valid_seats = input_seats.intersection(available_seats[movie_name])
        invalid_seats = input_seats.difference(available_seats[movie_name])

        if invalid_seats:
            print(f"The following seats are invalid or already taken: {', '.join(invalid_seats)}. Please choose from available seats.")

        if valid_seats:
            chosen_seats.update(valid_seats)
            print(f"Selected seats so far: {', '.join(sorted(list(chosen_seats)))}")
        else:
            if not invalid_seats:
                print("No valid seats entered. Please try again.")

    if chosen_seats:
        print(f"You have chosen: {', '.join(sorted(list(chosen_seats)))}")
    return chosen_seats

# --- 5. Booking and Payment ---
def book_tickets(username, movie_name, seats_to_book):
    if not seats_to_book:
        print("No seats selected for booking.")
        return 0, set()

    price_per_seat = movies[movie_name]["price"]
    total_cost = len(seats_to_book) * price_per_seat

    print(f"\n--- Booking Summary for {username} ---")
    print(f"Movie: {movie_name}")
    print(f"Seats: {', '.join(sorted(list(seats_to_book)))}")
    print(f"Price per seat: ${price_per_seat:.2f}")
    print(f"Total cost: ${total_cost:.2f}")

    confirm = input("Confirm booking? (yes/no): ").lower().strip()
    if confirm == 'yes':
        confirmed_seats = set()
        for seat in seats_to_book:
            if seat in available_seats[movie_name]:
                available_seats[movie_name].remove(seat)
                booked_seats[movie_name].add(seat)
                confirmed_seats.add(seat)
            else:
                print(f"Warning: Seat {seat} was no longer available. Booking for other seats proceeded.")

        if confirmed_seats:
            print("Booking confirmed! Enjoy your movie!")
            return len(confirmed_seats) * price_per_seat, confirmed_seats
        else:
            print("No seats could be booked as they became unavailable.")
            return 0, set()
    else:
        print("Booking cancelled.")
        return 0, set()

# --- 6. Main Program ---
def main():
    print("Welcome to the Movie Ticketing Platform!")

    # 1. User Login
    current_user = login()
    total_paid_overall = 0
    all_booked_tickets = []

    while True:
        # 2. Display Movies and Select Movie
        selected_movie = select_movie()

        # 3. Seat Selection
        selected_seats_for_movie = select_seats(selected_movie)

        # 4. Booking and Payment
        if selected_seats_for_movie:
            cost_for_booking, confirmed_seats = book_tickets(current_user, selected_movie, selected_seats_for_movie)
            if confirmed_seats: # Only add if seats were actually confirmed
                total_paid_overall += cost_for_booking
                all_booked_tickets.append({
                    "user": current_user,
                    "movie": selected_movie,
                    "seats": sorted(list(confirmed_seats)),
                    "cost": cost_for_booking
                })

        book_more = input("\nDo you want to book more tickets? (yes/no): ").lower().strip()
        if book_more != 'yes':
            break

    print("\n--- Your Total Booking Summary ---")
    if all_booked_tickets:
        for booking in all_booked_tickets:
            print(f"Movie: {booking['movie']}, Seats: {', '.join(booking['seats'])}, Cost: ${booking['cost']:.2f}")
        print(f"Total amount paid: ${total_paid_overall:.2f}")
    else:
        print("No tickets were booked.")
    print("Thank you for using our platform!")

# Run the main program
main()

def main():
    print("Welcome to the Movie Ticketing Platform!")

    # 1. User Login
    current_user = login()
    total_paid_overall = 0
    all_booked_tickets = []

    while True:
        # 2. Display Movies and Select Movie
        selected_movie = select_movie()

        # 3. Seat Selection
        selected_seats_for_movie = select_seats(selected_movie)

        # 4. Booking and Payment
        if selected_seats_for_movie:
            cost_for_booking, confirmed_seats = book_tickets(current_user, selected_movie, selected_seats_for_movie)
            if confirmed_seats:
                total_paid_overall += cost_for_booking
                all_booked_tickets.append({
                    "user": current_user,
                    "movie": selected_movie,
                    "seats": sorted(list(confirmed_seats)),
                    "cost": cost_for_booking
                })

        book_more = input("\nDo you want to book more tickets? (yes/no): ").lower().strip()
        if book_more != 'yes':
            break

    print("\n--- Your Total Booking Summary ---")
    if all_booked_tickets:
        for booking in all_booked_tickets:
            print(f"Movie: {booking['movie']}, Seats: {', '.join(booking['seats'])}, Cost: ${booking['cost']:.2f}")
        print(f"Total amount paid: ${total_paid_overall:.2f}")
    else:
        print("No tickets were booked.")
    print("Thank you for using our platform!")

# Run the main program
main()

def main():
    print("Welcome to the Movie Ticketing Platform!")

    current_user = login()
    total_paid_overall = 0
    all_booked_tickets = []

    while True:

        selected_movie = select_movie()


        selected_seats_for_movie = select_seats(selected_movie)


        if selected_seats_for_movie:
            cost_for_booking, confirmed_seats = book_tickets(current_user, selected_movie, selected_seats_for_movie)
            if confirmed_seats:
                total_paid_overall += cost_for_booking
                all_booked_tickets.append({
                    "user": current_user,
                    "movie": selected_movie,
                    "seats": sorted(list(confirmed_seats)),
                    "cost": cost_for_booking
                })

        book_more = input("\nDo you want to book more tickets? (yes/no): ").lower().strip()
        if book_more != 'yes':
            break

    print("\n--- Your Total Booking Summary ---")
    if all_booked_tickets:
        for booking in all_booked_tickets:
            print(f"Movie: {booking['movie']}, Seats: {', '.join(booking['seats'])}, Cost: ${booking['cost']:.2f}")
        print(f"Total amount paid: ${total_paid_overall:.2f}")
    else:
        print("No tickets were booked.")
    print("Thank you for using our platform!")


main()

import math

# --- 1. Data Initialization ---
movies = {
    "The Grand Adventure": {"price": 12.00, "seats": [
        "A1", "A2", "A3", "A4", "A5", "A6",
        "B1", "B2", "B3", "B4", "B5", "B6",
        "C1", "C2", "C3", "C4", "C5", "C6"
    ]},
    "Mystery of the Old House": {"price": 10.50, "seats": [
        "D1", "D2", "D3", "D4", "D5", "D6",
        "E1", "E2", "E3", "E4", "E5", "E6",
        "F1", "F2", "F3", "F4", "F5", "F6"
    ]},
    "Sci-Fi Odyssey": {"price": 15.00, "seats": [
        "G1", "G2", "G3", "G4", "G5", "G6",
        "H1", "H2", "H3", "H4", "H5", "H6",
        "I1", "I2", "I3", "I4", "I5", "I6"
    ]}
}

available_seats = {
    movie_name: set(details["seats"]) for movie_name, details in movies.items()
}

booked_seats = {
    movie_name: set() for movie_name in movies.keys()
}

users = {
    "user1": "pass1",
    "user2": "pass2",
    "alice": "password",
    "bob": "12345"
}

# --- 2. User Authentication ---
def login():
    attempts = 0
    while attempts < 3:
        username = input("Enter username: ").strip()
        password = input("Enter password: ").strip()

        if username in users and users[username] == password:
            print(f"Welcome, {username}!")
            return username
        else:
            print("Invalid username or password. Please try again.")
            attempts += 1
    print("Too many failed login attempts. Exiting.")
    exit()

# --- 3. Movie Selection ---
def display_movies():
    print("\n--- Available Movies ---")
    for movie, details in movies.items():
        print(f"- {movie} (Price: ${details['price']:.2f})")

def select_movie():
    while True:
        display_movies()
        chosen_movie = input("\nEnter the name of the movie you want to watch: ").strip()
        if chosen_movie in movies:
            print(f"You selected: {chosen_movie}")
            return chosen_movie
        else:
            print("Invalid movie name. Please choose from the list.")

# --- 4. Seat Selection ---
def display_available_seats(movie_name):
    print(f"\n--- Available Seats for {movie_name} ---")
    seats = sorted(list(available_seats[movie_name]))
    if not seats:
        print("No seats available for this movie.")
        return

    # Display seats in a grid-like format for better readability
    seats_per_row = 6 # You can adjust this number
    for i in range(0, len(seats), seats_per_row):
        print(" ".join(seats[i:i + seats_per_row]))

def select_seats(movie_name):
    chosen_seats = set()
    while True:
        display_available_seats(movie_name)
        if not available_seats[movie_name]:
            print("Sorry, no seats are available for this movie.")
            return set()

        seat_input = input("Enter the seat numbers you want to book (e.g., A1 B2), or 'done' to finish: ").upper().strip()
        if seat_input == 'DONE':
            break

        input_seats = set(seat_input.split())
        valid_seats = input_seats.intersection(available_seats[movie_name])
        invalid_seats = input_seats.difference(available_seats[movie_name])

        if invalid_seats:
            print(f"The following seats are invalid or already taken: {', '.join(invalid_seats)}. Please choose from available seats.")

        if valid_seats:
            chosen_seats.update(valid_seats)
            print(f"Selected seats so far: {', '.join(sorted(list(chosen_seats)))}")
        else:
            if not invalid_seats:
                print("No valid seats entered. Please try again.")

    if chosen_seats:
        print(f"You have chosen: {', '.join(sorted(list(chosen_seats)))}")
    return chosen_seats

# --- 5. Booking and Payment ---
def book_tickets(username, movie_name, seats_to_book):
    if not seats_to_book:
        print("No seats selected for booking.")
        return 0, set()

    price_per_seat = movies[movie_name]["price"]
    total_cost = len(seats_to_book) * price_per_seat

    print(f"\n--- Booking Summary for {username} ---")
    print(f"Movie: {movie_name}")
    print(f"Seats: {', '.join(sorted(list(seats_to_book)))}")
    print(f"Price per seat: ${price_per_seat:.2f}")
    print(f"Total cost: ${total_cost:.2f}")

    confirm = input("Confirm booking? (yes/no): ").lower().strip()
    if confirm == 'yes':
        confirmed_seats = set()
        for seat in seats_to_book:
            if seat in available_seats[movie_name]:
                available_seats[movie_name].remove(seat)
                booked_seats[movie_name].add(seat)
                confirmed_seats.add(seat)
            else:
                print(f"Warning: Seat {seat} was no longer available. Booking for other seats proceeded.")

        if confirmed_seats:
            print("Booking confirmed! Enjoy your movie!")
            return len(confirmed_seats) * price_per_seat, confirmed_seats
        else:
            print("No seats could be booked as they became unavailable.")
            return 0, set()
    else:
        print("Booking cancelled.")
        return 0, set()

# --- 6. Main Program ---
def main():
    print("Welcome to the Movie Ticketing Platform!")

    # 1. User Login
    current_user = login()
    total_paid_overall = 0
    all_booked_tickets = []

    while True:
        # 2. Display Movies and Select Movie
        selected_movie = select_movie()

        # 3. Seat Selection
        selected_seats_for_movie = select_seats(selected_movie)

        # 4. Booking and Payment
        if selected_seats_for_movie:
            cost_for_booking, confirmed_seats = book_tickets(current_user, selected_movie, selected_seats_for_movie)
            if confirmed_seats: # Only add if seats were actually confirmed
                total_paid_overall += cost_for_booking
                all_booked_tickets.append({
                    "user": current_user,
                    "movie": selected_movie,
                    "seats": sorted(list(confirmed_seats)),
                    "cost": cost_for_booking
                })

        book_more = input("\nDo you want to book more tickets? (yes/no): ").lower().strip()
        if book_more != 'yes':
            break

    print("\n--- Your Total Booking Summary ---")
    if all_booked_tickets:
        for booking in all_booked_tickets:
            print(f"Movie: {booking['movie']}, Seats: {', '.join(booking['seats'])}, Cost: ${booking['cost']:.2f}")
        print(f"Total amount paid: ${total_paid_overall:.2f}")
    else:
        print("No tickets were booked.")
    print("Thank you for using our platform!")

# Run the main program
main()





